# Site basics
title: Workflow
description: A simple portfolio & project site by Haider Ali
theme: jekyll-theme-minimal

# IMPORTANT for project sites (username.github.io/repo)
url: https://haiderxayan.github.io
baseurl: /workflow

# Optional niceties
show_downloads: false
author: Haider Ali

# GitHub Pages–safe plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# SEO
seo:
  type: Person
